### ISSUE TITLE
Video not play, but can hear sound

### ISSUE THREAD

**Issue by aainanewscorp** [BrightcoveOS/ios-player-samples#31]
While playing video in AVPlayer, it doesn't play video but play sound. By moving video from seek bar, we can see changes.

**Comment by sjbushell** [comment]
Can you tell us what project you're using? What OS version? iOS or tvOS?

**Comment by postmechanical** [comment]
Ditto. Just ran into this issue. Using the sample app. Xcode 9.2. tvOS 11.2.

**Comment by postmechanical** [comment]
@sjbushell Did you implement the following `BCOVPlaybackControllerDelegate` method?

```
		func playbackController(_ controller: BCOVPlaybackController!, didAdvanceTo session: BCOVPlaybackSession!)
		{
				NSLog("ViewController Debug - Advanced to new session.")
				self.avpvc.player = session.player;
		}
```

**Comment by sjbushell** [comment]
Going to close this since there's been no response from the original poster in 5 months.
This issue sounds like a problem that happens when using the AVPlayerViewController. If using the AVPlayerViewController, be sure to use the [AVPlayerViewController compatibility flag](https://github.com/brightcove/brightcove-player-sdk-ios/blob/ae93125d9c9e43de34521b778a15f2958fddba20/ios/dynamic/BrightcovePlayerSDK.framework/Headers/BCOVPlaybackController.h#L144-L150).
